### ISSUE TITLE
Add a _reindex example

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/elasticsearch-cheatsheet#12]
This API is very useful!

**Comment by anned20** [comment]
I can do this!

**Comment by damienalexandre** [comment]
@anned20 Sorry someone is already working on it: https://github.com/jolicode/elasticsearch-cheatsheet/pull/13

But I think this one is still available and quite easy: https://github.com/jolicode/elasticsearch-cheatsheet/issues/11

**Comment by anned20** [comment]
Ah, missed that @damienalexandre, I already made the pull request. Should I close it?

**Comment by damienalexandre** [comment]
Let's keep it open, I prefer your's actually :grimacing:

**Comment by damienalexandre** [comment]
Done in #13
