### ISSUE TITLE
Add direct links to the download pages

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/elasticsearch-cheatsheet#25]
Downloading Elasticsearch when coming from organic search or https://www.elastic.co/ homepage is more and more difficult; there is no direct link to the Elasticsearch download page.

We could provide them.

**Comment by rahuldkjain** [comment]
Hi @damienalexandre I would love to add the direct download links. Please assign this issue to me.

**Comment by pyrech** [comment]
Hey @rahuldkjain. Go for it :wink: 

Could you do it for all versions? Thanks :slightly_smiling_face:

**Comment by rahuldkjain** [comment]
@pyrech Could you please explain how it needs to be done for all versions?

**Comment by rahuldkjain** [comment]
@damienalexandre @pyrech  Please review the PR https://github.com/jolicode/elasticsearch-cheatsheet/pull/26
